chore(CI): use local playwright version for install
Otherwise we end up with messages like:

```
Error: browserType.launch: Executable doesn't exist at...
Looks like Playwright Test or Playwright was just installed or updated.
```

Because dlx never uses the local version and always use the remote.
Because when there's a playwright update, it will download new browser versions
while we've tried to use the local cache.